### ISSUE TITLE
Fehler User hinzufügen

### ISSUE THREAD

**Issue by Tilleleb** [Nitooo/KBA_Messenger_Server#2]
Wenn ich versuche über die GUI einen Benutzer hinzuzufügen, erhalte ich eine Fehlermeldung auf dem Client:
[Fehlermeldung-Client.txt](https://github.com/Nitooo/KBA_Messenger_Server/files/2340822/Fehlermeldung-Client.txt)

**Comment by Tilleleb** [comment]
Ich vermute, dass der Fehler irgendwo hier liegt
messenger.ServiceAdapter.UserManagementAdapter.addUser(UserManagementAdapter.java:25)
messenger.Gui.UserBean.addUser(UserBean.java:107)

**Comment by campbellbs** [comment]
line 22 in /KBA_Messenger_Client/src/main/java/messenger/ServiceAdapter/UserManagementAdapter.java modified from:
final String uri = "http://localhost:8081/messenger/userManagement/addUser.json";
to
final String uri = "http://localhost:8081/messenger/userManagement/addUser?username= " + username + "&passwort=" + passwort;

changed Bean to addUserBean to pass input values via addUserBean attributes. Shift method "addUser" from userBean to addUserBean.
